
import java.awt.HeadlessException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jefry Hernandez
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_logincorreo = new javax.swing.JTextField();
        pf_logincontra = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jd_CrearCuenta = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_mail = new javax.swing.JTextField();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        pf_password = new javax.swing.JPasswordField();
        pf_confirmr = new javax.swing.JPasswordField();
        tf_numero = new javax.swing.JTextField();
        cb_pais = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jd_mensajes = new javax.swing.JDialog();
        cb_buzon = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_mensajes = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jd_enviarmensajes = new javax.swing.JDialog();
        cb_enviar = new javax.swing.JComboBox<>();
        tf_asunto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jd_login2 = new javax.swing.JDialog();
        cb_usuaro = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        ta_asunto1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_mensaje2 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Login");

        jLabel12.setText("Correo");

        jLabel13.setText("Contraseña");

        jButton4.setText("Ingresar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(pf_logincontra))
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(43, 43, 43)
                                .addComponent(tf_logincorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton4)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_logincorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pf_logincontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(31, 31, 31))
        );

        jLabel2.setText("Creacion de usuario");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Correo");

        jLabel6.setText("Fecha de nacimiento");

        jLabel7.setText("Contraseña");

        jLabel8.setText("Confirmar Contraseña");

        jLabel9.setText("Pais");

        jLabel10.setText("Numero");

        cb_pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honduras", "Estados Unidos", "Mexico", "Canada", "Brasil", "Argentina" }));

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearCuentaLayout = new javax.swing.GroupLayout(jd_CrearCuenta.getContentPane());
        jd_CrearCuenta.getContentPane().setLayout(jd_CrearCuentaLayout);
        jd_CrearCuentaLayout.setHorizontalGroup(
            jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearCuentaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_nombre)
                    .addComponent(tf_apellido)
                    .addComponent(tf_mail)
                    .addComponent(dc_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pf_password)
                    .addComponent(pf_confirmr)
                    .addComponent(tf_numero)
                    .addComponent(cb_pais, 0, 118, Short.MAX_VALUE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jd_CrearCuentaLayout.setVerticalGroup(
            jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_CrearCuentaLayout.createSequentialGroup()
                        .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pf_confirmr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        cb_buzon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enviados", "Leidos", "No leidos", "Eliminados", "Borrador", "Spam", "Importantes", "No deseados", " ", " " }));
        cb_buzon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_buzonItemStateChanged(evt);
            }
        });

        jt_mensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receptor", "Mensaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_mensajes);

        jButton5.setText("Enviar mensajes");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton7.setText("Actualizar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("logout");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_mensajesLayout = new javax.swing.GroupLayout(jd_mensajes.getContentPane());
        jd_mensajes.getContentPane().setLayout(jd_mensajesLayout);
        jd_mensajesLayout.setHorizontalGroup(
            jd_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mensajesLayout.createSequentialGroup()
                .addGroup(jd_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mensajesLayout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mensajesLayout.createSequentialGroup()
                        .addGroup(jd_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_mensajesLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(cb_buzon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_mensajesLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton7)
                                .addGap(28, 28, 28)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_mensajesLayout.setVerticalGroup(
            jd_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mensajesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cb_buzon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel15.setText("Asunto");

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane2.setViewportView(ta_mensaje);

        jLabel16.setText("Mensaje");

        jButton6.setText("Enviar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_enviarmensajesLayout = new javax.swing.GroupLayout(jd_enviarmensajes.getContentPane());
        jd_enviarmensajes.getContentPane().setLayout(jd_enviarmensajesLayout);
        jd_enviarmensajesLayout.setHorizontalGroup(
            jd_enviarmensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_enviarmensajesLayout.createSequentialGroup()
                .addGroup(jd_enviarmensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_enviarmensajesLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel15)
                        .addGap(45, 45, 45)
                        .addGroup(jd_enviarmensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_enviar, 0, 126, Short.MAX_VALUE)
                            .addComponent(tf_asunto)))
                    .addGroup(jd_enviarmensajesLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_enviarmensajesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(150, 150, 150))
        );
        jd_enviarmensajesLayout.setVerticalGroup(
            jd_enviarmensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_enviarmensajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_enviarmensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGroup(jd_enviarmensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_enviarmensajesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_enviarmensajesLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jd_login2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jd_login2MouseClicked(evt);
            }
        });

        cb_usuaro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_usuaroItemStateChanged(evt);
            }
        });

        jLabel14.setText("Asunto");

        ta_mensaje2.setColumns(20);
        ta_mensaje2.setRows(5);
        jScrollPane3.setViewportView(ta_mensaje2);

        jLabel17.setText("mensaje");

        jButton9.setText("Enviar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_login2Layout = new javax.swing.GroupLayout(jd_login2.getContentPane());
        jd_login2.getContentPane().setLayout(jd_login2Layout);
        jd_login2Layout.setHorizontalGroup(
            jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_login2Layout.createSequentialGroup()
                .addGroup(jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jd_login2Layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jLabel14)
                            .addGap(51, 51, 51)
                            .addComponent(ta_asunto1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_login2Layout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addComponent(jButton9))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_login2Layout.createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addComponent(cb_usuaro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_login2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jd_login2Layout.setVerticalGroup(
            jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_login2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_usuaro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ta_asunto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_login2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_login2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel17)))
                .addGap(43, 43, 43)
                .addComponent(jButton9)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Crear cuenta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Sistema de registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        try {
            String nombre = tf_nombre.getText();
            String apelllido = tf_apellido.getText();
            String pais = cb_pais.getSelectedItem().toString();
            String correo = tf_mail.getText();
            String numero = tf_numero.getText();
            String contraseña = "";
            String fecha = dc_fecha.getDate().toString();
            if (!usuarios.contains(correo)) {
                if ((pf_password.getText().equals(pf_confirmr.getText())) && (!pf_password.equals(""))) {
                    contraseña = pf_password.getText();
                    usuarios.add(correo);
                    crearfolder(correo);
                    Usuario p = new Usuario(nombre, apelllido, contraseña, fecha, pais, numero, correo);
                    lista.add(p);

                    tf_nombre.setText("");
                    tf_apellido.setText("");
                    tf_mail.setText("");
                    tf_numero.setText("");
                    pf_confirmr.setText("");
                    pf_password.setText("");
                    dc_fecha.setDate(new Date());
                    jd_CrearCuenta.dispose();

                } else {
                    tf_nombre.setText("");
                    tf_apellido.setText("");
                    tf_mail.setText("");
                    tf_numero.setText("");
                    pf_confirmr.setText("");
                    pf_password.setText("");
                    dc_fecha.setDate(new Date());
                    JOptionPane.showMessageDialog(this, "Cambie su contraseña");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cambie su correo");
                tf_nombre.setText("");
                tf_apellido.setText("");
                tf_mail.setText("");
                tf_numero.setText("");
                pf_confirmr.setText("");
                pf_password.setText("");
                dc_fecha.setDate(new Date());
            }
        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(this, "No se pudo crear la cuenta");
        }


    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jd_CrearCuenta.setModal(true);
        jd_CrearCuenta.pack();
        jd_CrearCuenta.setLocationRelativeTo(this);
        jd_CrearCuenta.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jd_login.setModal(true);
        jd_login.pack();
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String correo = tf_logincorreo.getText();
        String contra = pf_logincontra.getText();
        for (Usuario us : lista) {
            if (us.getCorreo().equals(correo) && us.getContraseña().equals(contra) && correo.contains("@unitec.edu")) {
                JOptionPane.showMessageDialog(this, "Ingreso con exito");
                user = us;
                tf_logincorreo.setText("");
                pf_logincontra.setText("");
                jd_login.dispose();
                jd_mensajes.setModal(true);
                jd_mensajes.pack();
                jd_mensajes.setLocationRelativeTo(this);
                jd_mensajes.setVisible(true);

            } else if (us.getCorreo().equals(correo) && us.getContraseña().equals(contra)) {
                jd_login2.setModal(true);
                jd_login2.pack();
                jd_login2.setLocationRelativeTo(this);
                jd_login2.setVisible(true);
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_usuaro.getModel();
                for (Usuario ux : lista) {
                    if (ux != user) {
                        modelo.addElement(us);
                    }

                }
                jd_login.dispose();

            }
        }

        tf_logincorreo.setText("");
        pf_logincontra.setText("");


    }//GEN-LAST:event_jButton4MouseClicked

    private void cb_buzonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_buzonItemStateChanged
        if (evt.getStateChange() == 2) {
            DefaultTableModel model = (DefaultTableModel) jt_mensajes.getModel();
            if (cb_buzon.getSelectedItem().equals("No leidos")) {
                ArrayList<Mensaje> lista = user.getNo_leido();
                for (Mensaje me : lista) {
                    String[] row = {me.getEmisor(), me.getMensaje()};
                    model.addRow(row);
                }
            }
            if (cb_buzon.getSelectedItem().equals("Enviados")) {
                ArrayList<Mensaje> lista = user.getEnviado();
                for (Mensaje me : lista) {
                    String[] row = {me.getReceptor(), me.getMensaje()};
                    model.addRow(row);
                }
            }
            if (cb_buzon.getSelectedItem().equals("Leidos")) {
                ArrayList<Mensaje> lista = user.getLeido();
                for (Mensaje me : lista) {
                    String[] row = {me.getEmisor(), me.getMensaje()};
                    model.addRow(row);
                }
            }
            if (cb_buzon.getSelectedItem().equals("Importantes")) {
                ArrayList<Mensaje> lista = user.getImportante();
                for (Mensaje me : lista) {
                    String[] row = {me.getEmisor(), me.getMensaje()};
                    model.addRow(row);
                }
            }
            if (cb_buzon.getSelectedItem().equals("Eliminados")) {
                ArrayList<Mensaje> lista = user.getEliminado();
                for (Mensaje me : lista) {
                    String[] row = {me.getEmisor(), me.getMensaje()};
                    model.addRow(row);
                }
            }
            if (cb_buzon.getSelectedItem().equals("Borrador")) {
                ArrayList<Mensaje> lista = user.getBorrador();
                for (Mensaje me : lista) {
                    String[] row = {me.getEmisor(), me.getMensaje()};
                    model.addRow(row);
                }
            }
            if (cb_buzon.getSelectedItem().equals("Spam")) {
                ArrayList<Mensaje> lista = user.getSpam();
                for (Mensaje me : lista) {
                    String[] row = {me.getEmisor(), me.getMensaje()};
                    model.addRow(row);
                }
            }
            if (cb_buzon.getSelectedItem().equals("No deseados")) {
                ArrayList<Mensaje> lista = user.getNo_deseado();
                for (Mensaje me : lista) {
                    String[] row = {me.getEmisor(), me.getMensaje()};
                    model.addRow(row);
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_buzonItemStateChanged

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        jd_enviarmensajes.setModal(true);
        jd_enviarmensajes.pack();
        jd_enviarmensajes.setLocationRelativeTo(this);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_enviar.getModel();
        for (Usuario us : lista) {
            if (us != user) {
                modelo.addElement(us);
            }

        }
        jd_enviarmensajes.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        try {
            String receptor = cb_enviar.getSelectedItem().toString();
            String asunto = tf_asunto.getText();
            String mensaje = ta_mensaje.getText();
            Usuario emisor = new Usuario();

            Mensaje m = new Mensaje(receptor, user.getCorreo(), mensaje, asunto);
            for (Usuario us : lista) {
                if (us.getCorreo().equals(receptor)) {
                    emisor = us;
                }
            }
            emisor.getNo_leido().add(m);
            user.getEnviado().add(m);
            jd_enviarmensajes.dispose();
            jd_mensajes.setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked

    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        jd_mensajes.dispose();
        user = new Usuario();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void jd_login2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jd_login2MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jd_login2MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        String asunto = ta_asunto1.getText();
        String mensaje = ta_mensaje2.getText();
        String receptor = cb_usuaro.getSelectedItem().toString();
        Usuario rece = new Usuario();
        for (Usuario usuario : lista) {
            if (usuario.getCorreo().equals(receptor)) {
                rece = usuario;
            }
        }
        Mensaje m = new Mensaje(receptor, receptor, mensaje, asunto);
        rece.getNo_leido().add(m);
        user.getEnviado().add(m);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void cb_usuaroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_usuaroItemStateChanged
        if (evt.getStateChange() == 2) {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_usuaroItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_buzon;
    private javax.swing.JComboBox<String> cb_enviar;
    private javax.swing.JComboBox<String> cb_pais;
    private javax.swing.JComboBox<String> cb_usuaro;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_CrearCuenta;
    private javax.swing.JDialog jd_enviarmensajes;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_login2;
    private javax.swing.JDialog jd_mensajes;
    private javax.swing.JTable jt_mensajes;
    private javax.swing.JPasswordField pf_confirmr;
    private javax.swing.JPasswordField pf_logincontra;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField ta_asunto1;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextArea ta_mensaje2;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_asunto;
    private javax.swing.JTextField tf_logincorreo;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_numero;
    // End of variables declaration//GEN-END:variables
    ArrayList<String> usuarios = new ArrayList();
    ArrayList<Usuario> lista = new ArrayList();
    Usuario user;

    public void crearfolder(String nombre) throws IOException {
        File carpeta = new File(":/" + nombre);
        carpeta.mkdir();
        FileWriter fw;
        BufferedWriter bw;

        fw = new FileWriter("./usuario/" + nombre + "/leido.txt");
        bw = new BufferedWriter(fw);
        //leido.mkdir();
        fw = new FileWriter("./usuario/" + nombre + "/noleido.txt");
        bw = new BufferedWriter(fw);

        fw = new FileWriter("./usuario/" + nombre + "/spam.txt");
        bw = new BufferedWriter(fw);

        fw = new FileWriter("./usuario/" + nombre + "/eliminado.txt");
        bw = new BufferedWriter(fw);

        fw = new FileWriter("./usuario/" + nombre + "/borrador.txt");
        bw = new BufferedWriter(fw);

        fw = new FileWriter("./usuario/" + nombre + "/importantes.txt");
        bw = new BufferedWriter(fw);

        fw = new FileWriter("./usuario/" + nombre + "/enviado.txt");
        bw = new BufferedWriter(fw);

        fw = new FileWriter("./usuario/" + nombre + "/nodeseado.txt");
        bw = new BufferedWriter(fw);

    }

    public void llenararchivos() {
        FileWriter fw = null;
        BufferedWriter bw = null;
        File f = new File("./usuario/" + user.getCorreo() + "/enviado.txt");
        File f1 = new File("./usuario/" + user.getCorreo() + "/nodeseado.txt");
        File f2 = new File("./usuario/" + user.getCorreo() + "noleido.txt");
        File f3 = new File("./usuario/" + user.getCorreo() + "/importantes.txt");
        File f4 = new File("./usuario/" + user.getCorreo() + "/borrador.txt");
        File f5 = new File("./usuario/" + user.getCorreo() + "/spam.txt");
        File f6 = new File("./usuario/" + user.getCorreo() + "/leido.txt");
        File f7 = new File("./usuario/" + user.getCorreo() + "/eliminado.txt");
        try {
            fw = new FileWriter(f, false);
            bw = new BufferedWriter(fw);

            for (Mensaje m : user.getEnviado()) {
                bw.write(m.getReceptor() + ";");
                bw.write(m.getEmisor() + ";");
                bw.write(m.getMensaje() + ";");
                bw.write(m.getAsunto() + ";");
            }
            bw.flush();
            bw.close();

            fw = new FileWriter(f1, false);
            bw = new BufferedWriter(fw);

            for (Mensaje m : user.getNo_deseado()) {
                bw.write(m.getReceptor() + ";");
                bw.write(m.getEmisor() + ";");
                bw.write(m.getMensaje() + ";");
                bw.write(m.getAsunto() + ";");
            }
            bw.flush();
            bw.close();

            fw = new FileWriter(f2, false);
            bw = new BufferedWriter(fw);

            for (Mensaje m : user.getNo_leido()) {
                bw.write(m.getReceptor() + ";");
                bw.write(m.getEmisor() + ";");
                bw.write(m.getMensaje() + ";");
                bw.write(m.getAsunto() + ";");
            }
            bw.flush();
            bw.close();

            fw = new FileWriter(f3, false);
            bw = new BufferedWriter(fw);

            for (Mensaje m : user.getImportante()) {
                bw.write(m.getReceptor() + ";");
                bw.write(m.getEmisor() + ";");
                bw.write(m.getMensaje() + ";");
                bw.write(m.getAsunto() + ";");
            }
            bw.flush();
            bw.close();

            fw = new FileWriter(f4, false);
            bw = new BufferedWriter(fw);
            for (Mensaje m : user.getBorrador()) {
                bw.write(m.getReceptor() + ";");
                bw.write(m.getEmisor() + ";");
                bw.write(m.getMensaje() + ";");
                bw.write(m.getAsunto() + ";");
            }
            bw.flush();
            bw.close();

            fw = new FileWriter(f5, false);
            bw = new BufferedWriter(fw);
            for (Mensaje m : user.getSpam()) {
                bw.write(m.getReceptor() + ";");
                bw.write(m.getEmisor() + ";");
                bw.write(m.getMensaje() + ";");
                bw.write(m.getAsunto() + ";");
            }
            bw.flush();
            bw.close();

            fw = new FileWriter(f6, false);
            bw = new BufferedWriter(fw);
            for (Mensaje m : user.getLeido()) {
                bw.write(m.getReceptor() + ";");
                bw.write(m.getEmisor() + ";");
                bw.write(m.getMensaje() + ";");
                bw.write(m.getAsunto() + ";");
            }
            bw.flush();
            bw.close();

            fw = new FileWriter(f7, false);
            bw = new BufferedWriter(fw);
            for (Mensaje m : user.getEliminado()) {
                bw.write(m.getReceptor() + ";");
                bw.write(m.getEmisor() + ";");
                bw.write(m.getMensaje() + ";");
                bw.write(m.getAsunto() + ";");
            }
            bw.flush();
            bw.close();

        } catch (IOException e) {
        }

    }

    public void cargararraylist() {

        Scanner sc = null;

        try {
            File f = new File("./usuario/" + user.getCorreo() + "/enviado.txt");
            File f1 = new File("./usuario/" + user.getCorreo() + "/nodeseado.txt");
            File f2 = new File("./usuario/" + user.getCorreo() + "noleido.txt");
            File f3 = new File("./usuario/" + user.getCorreo() + "/importantes.txt");
            File f4 = new File("./usuario/" + user.getCorreo() + "/borrador.txt");
            File f5 = new File("./usuario/" + user.getCorreo() + "/spam.txt");
            File f6 = new File("./usuario/" + user.getCorreo() + "/leido.txt");
            File f7 = new File("./usuario/" + user.getCorreo() + "/eliminado.txt");
            sc = new Scanner(f);
            sc.useDelimiter(";");

            while (sc.hasNext()) {

                String receptor = sc.next();
                String emisor = sc.next();
                String mensaje = sc.next();
                String asunto = sc.next();
                user.getEnviado().add(new Mensaje(receptor, emisor, mensaje, asunto));
            }
            sc.close();

            sc = new Scanner(f1);
            sc.useDelimiter(";");
            while (sc.hasNext()) {

                String receptor = sc.next();
                String emisor = sc.next();
                String mensaje = sc.next();
                String asunto = sc.next();
                user.getNo_deseado().add(new Mensaje(receptor, emisor, mensaje, asunto));
            }
            sc.close();

            sc = new Scanner(f2);
            sc.useDelimiter(";");
            while (sc.hasNext()) {
                String receptor = sc.next();
                String emisor = sc.next();
                String mensaje = sc.next();
                String asunto = sc.next();
                user.getNo_leido().add(new Mensaje(receptor, emisor, mensaje, asunto));
            }
            sc.close();

            sc = new Scanner(f3);
            sc.useDelimiter(";");
            while (sc.hasNext()) {

                String receptor = sc.next();
                String emisor = sc.next();
                String mensaje = sc.next();
                String asunto = sc.next();
                user.getImportante().add(new Mensaje(receptor, emisor, mensaje, asunto));
            }
            sc.close();

            sc = new Scanner(f4);
            sc.useDelimiter(";");
            while (sc.hasNext()) {
                String receptor = sc.next();
                String emisor = sc.next();
                String mensaje = sc.next();
                String asunto = sc.next();
                user.getBorrador().add(new Mensaje(receptor, emisor, mensaje, asunto));
            }
            sc.close();

            sc = new Scanner(f5);
            sc.useDelimiter(";");
            while (sc.hasNext()) {
                String receptor = sc.next();
                String emisor = sc.next();
                String mensaje = sc.next();
                String asunto = sc.next();
                user.getSpam().add(new Mensaje(receptor, emisor, mensaje, asunto));
            }
            sc.close();

            sc = new Scanner(f6);
            sc.useDelimiter(";");
            while (sc.hasNext()) {
                String receptor = sc.next();
                String emisor = sc.next();
                String mensaje = sc.next();
                String asunto = sc.next();
                user.getLeido().add(new Mensaje(receptor, emisor, mensaje, asunto));
            }
            sc.close();

            sc = new Scanner(f7);
            sc.useDelimiter(";");
            while (sc.hasNext()) {

                String receptor = sc.next();
                String emisor = sc.next();
                String mensaje = sc.next();
                String asunto = sc.next();
                user.getEliminado().add(new Mensaje(receptor, emisor, mensaje, asunto));
            }
            sc.close();

        } catch (Exception e) {
        }
    }

    public void usuarioarchivo(Usuario u) {
        FileWriter fw;
        BufferedWriter bw;
        File f = null;
        try {
            fw = new FileWriter("./usuario/usuario.txt", true);
            bw = new BufferedWriter(fw);
            bw.write(u.getNombre() + ";");
            bw.write(u.getApellido() + ";");
            bw.write(u.getContraseña() + ";");
            bw.write(u.getFecha() + ";");
            bw.write(u.getPais() + ";");
            bw.write(u.getNumero() + ";");
            bw.write(u.getCorreo() + ";");
        } catch (Exception e) {
        }

    }

}
